name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y libx11-dev libxrandr-dev xserver-xorg-dev libxinerama-dev

    - name: make
      run: ./build.sh

    - name: make debug
      run: ./build.sh debug
